In [10]:
import pandas as pd

df_clients = pd.read_csv("../data/raw/clients.csv")
df_orders = pd.read_csv("../data/raw/orders.csv")
df_peyments = pd.read_csv("../data/raw/payments.csv")
df_products = pd.read_csv("../data/raw/products.csv")

display(df_clients.head())
display(df_clients.info())
display(df_clients.describe())
display(df_clients.isnull().sum())
display(df_clients.duplicated().sum())

,cliente_id,nome,sobrenome,sexo,idade,email,telefone,cidade,estado,data_cadastro
0,1,Arthur,Santos,M,19,arthur.santos755@gmail.com,(65)91520-1488,Rio de Janeiro,SP,2025-02-23
1,2,Theo,Teixeira,F,52,theo.teixeira829@gmail.com,(46)93547-4527,Florianópolis,PR,2023-12-06
2,3,João,Freitas,F,47,joão.freitas301@outlook.com,abc123,Londrina,RJ,2024-02-18
3,4,Arthur,Carvalho,M,28,arthur.carvalho719@gmail.com,(31)98573-7216,Curitiba,MT,2023-03-26
4,5,Caio,Moreira,M,21,NaN,(94)99179-7482,Goiânia,CE,2025-02-23

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   cliente_id     1000 non-null   int64
 1   nome           1000 non-null   str
 2   sobrenome      1000 non-null   str
 3   sexo           1000 non-null   str
 4   idade          941 non-null    str
 5   email          985 non-null    str
 6   telefone       927 non-null    str
 7   cidade         938 non-null    str
 8   estado         1000 non-null   str
 9   data_cadastro  1000 non-null   str
dtypes: int64(1), str(9)
memory usage: 78.3 KB

None

        cliente_id
count  1000.000000
mean    500.500000
std     288.819436
min       1.000000
25%     250.750000
50%     500.500000
75%     750.250000
max    1000.000000

cliente_id        0
nome              0
sobrenome         0
sexo              0
idade            59
email            15
telefone         73
cidade           62
estado            0
data_cadastro     0
dtype: int64

np.int64(0)

In [11]:
display(df_orders.head())
display(df_orders.info())
display(df_orders.describe())
display(df_orders.isnull().sum())
display(df_orders.duplicated().sum())

,pedido_id,cliente_id,produto_id,quantidade,preco_unitario,desconto,frete,valor_total,status,data_pedido
0,1,655,115,1,11128.43,NaN,29.54,10378.98,PAGO,2025-02-23
1,2,666,719,9,6304.41,0.13,48.95,49412.48,PAGO,2022-07-09
2,3,368,868,6,9063.82,0.24,112.16,41443.18,PENDENTE,05-23-2022
3,4,792,297,2,12832.66,0.26,63.22,19055.56,PAGO,2022-12-17
4,5,251,168,8,5704.24,0.30,NaN,32043.34,CANCELADO,2022-05-16

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pedido_id       10000 non-null  int64
 1   cliente_id      10000 non-null  int64
 2   produto_id      10000 non-null  int64
 3   quantidade      9814 non-null   str
 4   preco_unitario  10000 non-null  float64
 5   desconto        9490 non-null   float64
 6   frete           9482 non-null   float64
 7   valor_total     9858 non-null   str
 8   status          9886 non-null   str
 9   data_pedido     10000 non-null  str
dtypes: float64(3), int64(3), str(4)
memory usage: 781.4 KB

None

,pedido_id,cliente_id,produto_id,preco_unitario,desconto,frete
count,10000.00000,10000.000000,10000.000000,10000.000000,9490.000000,9482.000000
mean,5000.50000,557.565900,560.679800,7538.146114,0.149749,80.394933
std,2886.89568,344.771892,342.960098,4329.747220,0.086552,40.568602
min,1.00000,1.000000,1.000000,20.790000,0.000000,10.040000
25%,2500.75000,270.000000,276.000000,3785.835000,0.070000,45.567500
50%,5000.50000,534.000000,545.000000,7558.170000,0.150000,80.720000
75%,7500.25000,812.000000,812.000000,11306.780000,0.220000,115.517500
max,10000.00000,1500.000000,1500.000000,14999.970000,0.300000,149.970000

pedido_id           0
cliente_id          0
produto_id          0
quantidade        186
preco_unitario      0
desconto          510
frete             518
valor_total       142
status            114
data_pedido         0
dtype: int64

np.int64(0)

In [12]:
display(df_peyments.head())
display(df_peyments.info())
display(df_peyments.describe())
display(df_peyments.isnull().sum())
display(df_peyments.duplicated().sum())

,pagamento_id,pedido_id,forma_pagamento,parcelas,bandeira_cartao,valor_pago,status,data_pagamento
0,1,1825,PIX,12,NaN,4139.94,PAGO,2022-02-24
1,2,8929,Dinheiro,4,NaN,6749.15,PENDENTE,2024-01-06
2,3,9892,Boleto,1,NaN,10951.38,ESTORNADO,2022-04-04
3,4,4742,PIX,4,NaN,12999.93,PENDENTE,2022-12-17
4,5,4011,Cartão,8,NaN,5704.24,ESTORNADO,2023-03-09

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pagamento_id     10000 non-null  int64
 1   pedido_id        10000 non-null  int64
 2   forma_pagamento  9880 non-null   str
 3   parcelas         9391 non-null   str
 4   bandeira_cartao  1924 non-null   str
 5   valor_pago       9397 non-null   str
 6   status           9883 non-null   str
 7   data_pagamento   10000 non-null  str
dtypes: int64(2), str(6)
memory usage: 625.1 KB

None

       pagamento_id     pedido_id
count   10000.00000  10000.000000
mean     5000.50000   5513.763000
std      2886.89568   3205.663279
min         1.00000      1.000000
25%      2500.75000   2789.250000
50%      5000.50000   5526.000000
75%      7500.25000   8154.000000
max     10000.00000  12000.000000

pagamento_id          0
pedido_id             0
forma_pagamento     120
parcelas            609
bandeira_cartao    8076
valor_pago          603
status              117
data_pagamento        0
dtype: int64

np.int64(0)

In [14]:
display(df_products.head())
display(df_products.info())
display(df_products.isnull().sum())
display(df_products.duplicated().sum())
display(df_products['nome'].unique())

,produto_id,nome,categoria,marca,preco,estoque,data_cadastro
0,1,Mouse Gamer,Fonte,Logitech,9598.61,12,2025-01-21
1,2,Fonte 650W,NaN,Logitech,6340.39,15,2025-01-21
2,3,Headset Gamer,SSD,LG,6749.15,-10,2023-03-17
3,4,Memória 16GB,Headset,Dell,5062.19,47,2024-07-29
4,5,Fonte 650W,HD,Kingston,mil,193,2023-01-29

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   produto_id     1000 non-null   int64
 1   nome           1000 non-null   str
 2   categoria      985 non-null    str
 3   marca          1000 non-null   str
 4   preco          981 non-null    str
 5   estoque        980 non-null    str
 6   data_cadastro  1000 non-null   str
dtypes: int64(1), str(6)
memory usage: 54.8 KB

None

produto_id        0
nome              0
categoria        15
marca             0
preco            19
estoque          20
data_cadastro     0
dtype: int64

np.int64(0)

<StringArray>
[     'Mouse Gamer',       'Fonte 650W',    'Headset Gamer',
     'Memória 16GB',        'SSD 240GB',       'Fonte 750W',
         'RTX 4060',          'SSD 1TB',       'Monitor 24',
          'Core i5', 'Impressora Laser',           'HD 2TB',
       'Monitor 27',  'Notebook Office',          'Core i7',
         'RTX 4070',          'RX 7600',    'Mouse Sem Fio',
          'Ryzen 5',          'Ryzen 7',      'Memória 8GB',
   'Notebook Gamer',     'Gabinete RGB', 'Teclado Mecânico',
        'Webcam HD']
Length: 25, dtype: str